repos:
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.28.0
    hooks:
      - id: gitleaks
        name: gitleaks (secrets scan)
        args: ["detect", "--staged", "--redact", "--config=.gitleaks.toml"]
        stages: [pre-commit, pre-push]

