services:
  scandy-app-scandy:
    build:
      context: .
      dockerfile: Dockerfile.https
    image: scandy-local:dev-scandy
    container_name: scandy-app-scandy
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://admin:rdDeW85SpDJ5OOLkQt8vAtBCd@scandy-mongodb-scandy:27017/scandy_scandy?authSource=admin
      - MONGODB_DB=scandy_scandy
      - SECRET_KEY=azDs5kZcymluAY6HTnFdJSRFxINLzUWrs5QCj4H43PBumc46Af8ujoCTBKJBKtw3zGVGkBMg
      - FLASK_ENV=production
      - SYSTEM_NAME=Scandy scandy
      - TICKET_SYSTEM_NAME=Aufgaben scandy
      - TOOL_SYSTEM_NAME=Werkzeuge scandy
      - CONSUMABLE_SYSTEM_NAME=Verbrauchsgüter scandy
      - SESSION_COOKIE_SECURE=True
      - REMEMBER_COOKIE_SECURE=True
      - FORCE_HTTPS=True
      - SSL_CERT_PATH=/app/ssl/cert.pem
      - SSL_KEY_PATH=/app/ssl/key.pem
      - TZ=Europe/Berlin
    depends_on:
      scandy-mongodb-scandy:
        condition: service_healthy
    volumes:
      - ./app:/app/app
      - ./uploads:/app/app/uploads
      - ./backups:/app/app/backups
      - ./logs:/app/app/logs
      - ./ssl:/app/ssl
    healthcheck:
      test: ["CMD", "curl", "-f", "https://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  scandy-mongodb-scandy:
    image: mongo:7
    container_name: scandy-mongodb-scandy
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=rdDeW85SpDJ5OOLkQt8vAtBCd
      - MONGO_INITDB_DATABASE=scandy_scandy
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  scandy-mongo-express-scandy:
    image: mongo-express:1.0.0
    container_name: scandy-mongo-express-scandy
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rdDeW85SpDJ5OOLkQt8vAtBCd
      - ME_CONFIG_MONGODB_URL=mongodb://admin:rdDeW85SpDJ5OOLkQt8vAtBCd@scandy-mongodb-scandy:27017/
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123
    depends_on:
      scandy-mongodb-scandy:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  mongodb_data:
    driver: local 