services:
  mongodb-scandy:
    image: mongo:7
    container_name: scandy-mongodb-scandy
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_scandy:/data/db
      - app_backups_scandy:/backup
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - scandy-network-scandy
    command: mongod --bind_ip_all
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 10s
      retries: 15
      start_period: 30s
    env_file:
      - .env

  mongo-express-scandy:
    image: mongo-express:1.0.0
    container_name: scandy-mongo-express-scandy
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb-scandy:27017/
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "8081:8081"
    depends_on:
      mongodb-scandy:
        condition: service_healthy
    networks:
      - scandy-network-scandy
    env_file:
      - .env

  app-scandy:
    build:
      context: .
      dockerfile: Dockerfile
    image: scandy-local:dev-scandy
    container_name: scandy-app-scandy
    restart: unless-stopped
    environment:
      - DATABASE_MODE=mongodb
      - MONGODB_URI=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb-scandy:27017/${MONGODB_DB}
      - MONGODB_DB=${MONGODB_DB}
      - FLASK_ENV=production
      - SECRET_KEY=${SECRET_KEY}
      - SYSTEM_NAME=${SYSTEM_NAME}
      - TICKET_SYSTEM_NAME=${TICKET_SYSTEM_NAME}
      - TOOL_SYSTEM_NAME=${TOOL_SYSTEM_NAME}
      - CONSUMABLE_SYSTEM_NAME=${CONSUMABLE_SYSTEM_NAME}
      - CONTAINER_NAME=${CONTAINER_NAME}
      - TZ=Europe/Berlin
      - SESSION_COOKIE_SECURE=False
      - REMEMBER_COOKIE_SECURE=False
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app/app
      - app_uploads_scandy:/app/app/uploads
      - app_backups_scandy:/app/app/backups
      - app_logs_scandy:/app/app/logs
      - app_sessions_scandy:/app/app/flask_session
    depends_on:
      mongodb-scandy:
        condition: service_healthy
    networks:
      - scandy-network-scandy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    env_file:
      - .env

volumes:
  mongodb_data_scandy:
    driver: local
  app_uploads_scandy:
    driver: local
  app_backups_scandy:
    driver: local
  app_logs_scandy:
    driver: local
  app_sessions_scandy:
    driver: local

networks:
  scandy-network-scandy:
    driver: bridge
