services:
  scandy-app-scandy:
    build:
      context: .
      dockerfile: Dockerfile.https
    image: scandy-local:dev-scandy
    container_name: scandy-app-scandy
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - FLASK_ENV=production
      - SESSION_COOKIE_SECURE=True
      - REMEMBER_COOKIE_SECURE=True
      - FORCE_HTTPS=True
      - SSL_CERT_PATH=/app/ssl/cert.pem
      - SSL_KEY_PATH=/app/ssl/key.pem
      - TZ=Europe/Berlin
    depends_on:
      scandy-mongodb-scandy:
        condition: service_healthy
    volumes:
      - ./app:/app/app
      - ./uploads:/app/app/uploads
      - ./backups:/app/app/backups
      - ./logs:/app/app/logs
      - ./ssl:/app/ssl
    healthcheck:
      test: ["CMD", "curl", "-f", "https://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  scandy-mongodb-scandy:
    image: mongo:7
    container_name: scandy-mongodb-scandy
    restart: unless-stopped
    ports:
      - "27017:27017"
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGODB_DB}
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  scandy-mongo-express-scandy:
    image: mongo-express:1.0.0
    container_name: scandy-mongo-express-scandy
    restart: unless-stopped
    ports:
      - "8081:8081"
    env_file:
      - .env
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - ME_CONFIG_MONGODB_URL=${ME_CONFIG_MONGODB_URL}
      - ME_CONFIG_BASICAUTH_USERNAME=${ME_CONFIG_BASICAUTH_USERNAME}
      - ME_CONFIG_BASICAUTH_PASSWORD=${ME_CONFIG_BASICAUTH_PASSWORD}
    depends_on:
      scandy-mongodb-scandy:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  mongodb_data:
    driver: local 