version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: scandy-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: scandy123
      MONGO_INITDB_DATABASE: scandy
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - scandy-network
    command: mongod --auth --bind_ip_all

  mongo-express:
    image: mongo-express:1.0.0
    container_name: scandy-mongo-express
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: scandy123
      ME_CONFIG_MONGODB_URL: mongodb://admin:scandy123@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: scandy123
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    networks:
      - scandy-network

  scandy-app:
    build: .
    container_name: scandy-app-mongodb
    restart: unless-stopped
    environment:
      - DATABASE_MODE=mongodb
      - MONGODB_URI=mongodb://admin:scandy123@mongodb:27017/
      - MONGODB_DB=scandy
      - FLASK_ENV=production
      - SECRET_KEY=your-secret-key-here
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
      - ./uploads:/app/uploads
      - ./backups:/app/backups
    depends_on:
      - mongodb
    networks:
      - scandy-network

volumes:
  mongodb_data:
    driver: local

networks:
  scandy-network:
    driver: bridge 