version: '3.8'

services:
  scandy:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=mongodb://mongodb:27017/scandy
      - TICKETS_DATABASE_URL=mongodb://mongodb:27017/scandy_tickets
      - SECRET_KEY=your-secret-key-here
      - MONGODB_URI=mongodb://mongodb:27017/
    volumes:
      - ./app/static:/app/app/static
      - ./app/uploads:/app/app/uploads
      - ./app/logs:/app/app/logs
      - ./app/backups:/app/app/backups
    depends_on:
      - mongodb
    restart: unless-stopped
    command: >
      sh -c "
      mkdir -p /app/database &&
      python -m flask run --host=0.0.0.0 --port=5000
      "

  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    restart: unless-stopped

volumes:
  mongodb_data:

networks:
  scandy_network:
    driver: bridge 