version: '3.8'

services:
  # MongoDB für Test
  mongodb-test:
    image: mongo:6.0
    container_name: scandy-mongodb-test
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: scandy_test
    ports:
      - "27019:27017"  # Anderer Port als Produktion
    volumes:
      - mongodb_test_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - scandy-test-network

  # Scandy App für Test
  scandy-test:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scandy-app-test
    restart: unless-stopped
    environment:
      FLASK_ENV: development
      FLASK_DEBUG: 1
      MONGODB_URI: mongodb://admin:password123@mongodb-test:27017/scandy_test?authSource=admin
      MONGODB_DB: scandy_test
      SECRET_KEY: test-secret-key-change-in-production
    ports:
      - "5002:5000"  # Anderer Port als Produktion
    volumes:
      - ./app:/app/app
      - ./backups:/app/backups
      - ./static:/app/static
    depends_on:
      - mongodb-test
    networks:
      - scandy-test-network

volumes:
  mongodb_test_data:
    driver: local

networks:
  scandy-test-network:
    driver: bridge 