version: '3.8'

services:
  scandy:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=sqlite:////app/database/inventory.db
      - TICKETS_DATABASE_URL=sqlite:////app/database/tickets.db
      - SYSTEM_NAME=Scandy
      - TICKET_SYSTEM_NAME=Aufgaben
      - TOOL_SYSTEM_NAME=Werkzeuge
      - CONSUMABLE_SYSTEM_NAME=Verbrauchsgüter
    volumes:
      - ./uploads:/app/uploads
      - ./backups:/app/backups
    depends_on:
      - scandy_db
    restart: unless-stopped

  scandy_db:
    build: .
    command: >
      bash -c "mkdir -p /app/database && 
               touch /app/database/inventory.db /app/database/tickets.db && 
               chmod 666 /app/database/inventory.db /app/database/tickets.db && 
               tail -f /dev/null"
    restart: unless-stopped

networks:
  scandy_network:
    driver: bridge 